# -*- coding: utf-8 -*-
"""Copy of Connect Linkedin with cookie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbFI1QUjPJiU3kliY8qOVLAp36kJ1kUb

# **CÀI ĐẶT THƯ VIỆN CẦN THIẾT**
"""



import os
import base64
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
#from IPython.display import Image, display
from dotenv import load_dotenv
import pickle
from PIL import Image
# === GOOGLE SHEETS LOCAL SETUP ===
import pickle
import pandas as pd
import requests
from googleapiclient.discovery import build
from google.oauth2 import service_account
# === GOOGLE SHEETS LOCAL SETUP ===
import pickle
import random
import json
import pandas as pd
import requests
from googleapiclient.discovery import build
from google.oauth2 import service_account
# === FastAPI API ===

load_dotenv()

# --- CONFIG ---
MISSIVE_API_KEY = os.getenv('MISSIVE_API_KEY')
HEADERS = {"Authorization": f"Bearer {MISSIVE_API_KEY}", "Content-Type": "application/json"}
PARAMS = {"limit": 20, "inbox":"true"} 
COOKIES_FILE = 'linkedin_cookies.pkl'
CREDENTIALS_FILE = 'linkedin_credentials.pkl'
MAX_LIMIT = 15
SPREADSHEET_ID = os.getenv('SPREADSHEET_ID')
RANGE_NAME = "Sheet1!A:E"
GOOGLE_CREDS = os.getenv('GOOGLE_APPLICATION_CRED')

"""# **HÀM HỖ TRỢ**"""
def press_multiple_tab(actions,number_of_presses, wait_time):
    for i in range(number_of_presses):
        actions.send_keys(Keys.TAB).perform()
        time.sleep(wait_time)

def get_missive_linkedin_code():
    response = requests.get("https://public.missiveapp.com/v1/conversations", headers=HEADERS, params=PARAMS)
    if response.status_code != 200:
        return f"Lỗi API: {response.status_code}"
    conversations = response.json().get("conversations", [])
    temp = [c['latest_message_subject'] for c in conversations if 'name' in c['authors'][0] and c['authors'][0]['name'] == 'LinkedIn']
    final_temp = [f.split(' ')[-1:][0] for f in temp]
    for item in final_temp:
        if item.isdigit():
            return item
    return None
    
# def restore_cookie_from_secret():
#     raw_cookie = os.getenv('RAW_COOKIE_BASE64')
#     # Chỉ tạo file nếu chưa có (để ưu tiên cache của GitHub)
#     if raw_cookie and not os.path.exists('linkedin_cookies.pkl'):
#         with open('linkedin_cookies.pkl', 'wb') as f:
#             f.write(base64.b64decode(raw_cookie))
#         print("✅ Đã tạo file linkedin_cookies.pkl từ GitHub Secret!")
        
def human_type(element, text):
    """Gõ phím như người thật với độ trễ ngẫu nhiên"""
    for char in text:
        element.send_keys(char)
        time.sleep(random.uniform(0.1, 0.3))
# # def display_screenshot(driver: webdriver.Chrome, file_name: str = 'screenshot.png'):
# #     driver.save_screenshot(file_name)
# #     time.sleep(5)
# #     display(Image(filename=file_name))
# def display_full_screenshot(driver):
#     # Wait for the body element to be present
#     WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.TAG_NAME, "body")))

#     # Lấy chiều cao của trang (toàn bộ nội dung)
#     total_height = driver.execute_script("return document.body.scrollHeight")

#     # Điều chỉnh chiều cao của cửa sổ trình duyệt để khớp với chiều cao của trang
#     driver.set_window_size(1920, total_height)  # Đặt chiều rộng và chiều cao mong muốn

#     # Chụp ảnh màn hình
#     driver.save_screenshot('screenshot.png')

#     # Hiển thị ảnh chụp màn hình
#     # time.sleep(2)  # Đợi ảnh được lưu
#     # display(Image.open('screenshot.png'))

"""# **KẾT NỐI GOOGLE SHEETS**"""

def get_gsheet_service():
    scopes = ['https://www.googleapis.com/auth/spreadsheets']
    info = json.loads(GOOGLE_CREDS)
    creds = service_account.Credentials.from_service_account_info(info, scopes=scopes)
    service = build('sheets', 'v4', credentials=creds)
    return service

service = get_gsheet_service()
sheet = service.spreadsheets()
result = sheet.values().get(spreadsheetId=SPREADSHEET_ID, range=RANGE_NAME).execute()
values = result.get('values', [])
max_cols = max(len(row) for row in values) if values else 0
values = [row + [''] * (max_cols - len(row)) for row in values]
df = pd.DataFrame(values[1:], columns=values[0] if values else [])
df = df.fillna('')

"""# **HIỂN THỊ KẾT QUẢ GOOGLE SHEETS**"""
# df.head()

"""# **CẤU HÌNH DRIVER**"""


def get_driver():
    options = webdriver.ChromeOptions()
    
    # 1. Định nghĩa một User-Agent nhất quán (Tránh khai báo 2 lần)
    user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    options.add_argument(f"user-agent={user_agent}")

    # 2. Các thiết lập cơ bản cho môi trường Linux/Docker (GitHub Actions)
    options.add_argument('--no-sandbox')
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument('--disable-gpu')
    options.add_argument('--headless=new')
    options.add_argument("--window-size=1920,1200")
    
    # 3. CHỐNG PHÁT HIỆN BOT (Stealth Mode)
    # Loại bỏ cờ 'nút điều khiển tự động'
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option('useAutomationExtension', False)
    # Vô hiệu hóa tính năng AutomationControlled của Blink
    options.add_argument("--disable-blink-features=AutomationControlled")
    
    # Thêm các cờ để trình duyệt giống người dùng thật hơn
    options.add_argument("--disable-infobars")
    options.add_argument("--disable-notifications")
    
    # Khởi tạo driver
    driver = webdriver.Chrome(options=options)
    
    # 4. Ẩn thuộc tính navigator.webdriver bằng Script thực thi ngay khi load trang
    driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
        "source": """
            Object.defineProperty(navigator, 'webdriver', {
                get: () => undefined
            })
        """
    })
    
    return driver

"""# **HÀM ĐĂNG NHẬP**"""

def save_cookies(driver):
    """Lưu cookies vào file"""
    with open(COOKIES_FILE, "wb") as cookies_file:
        pickle.dump(driver.get_cookies(), cookies_file)
    print("INFO: COOKIES SAVED!")

def load_cookies(driver: webdriver.Chrome, file_name: str):
    """Đọc cookies từ file pickle và thêm vào browser"""
    if os.path.exists(file_name):
        with open(file_name, 'rb') as f:
            cookies = pickle.load(f)
            for cookie in cookies:
                driver.add_cookie(cookie)
                
def login_with_cookie(driver):
    """Xử lý đăng nhập bằng Cookie li_at từ .env"""
    print("INFO: Đang thử đăng nhập bằng Cookie...")
    # Bước 1: Vào domain LinkedIn trước để trình duyệt chấp nhận cookie
    driver.get("https://www.linkedin.com/login")
    time.sleep(3)

    li_at_cookie = os.getenv("LINKEDIN_COOKIE")
    
    if li_at_cookie:
        try:
            driver.delete_all_cookies()
            driver.add_cookie({
                "name": "li_at",
                "value": li_at_cookie,
                "domain": ".linkedin.com",
                "path": "/",
                "secure": True
            })
            
            # Bước 2: Refresh vào trang Feed
            driver.get("https://www.linkedin.com/feed/")
            time.sleep(5)
            
            # Bước 3: Kiểm tra xem đã vào được Feed chưa (tránh trường hợp cookie hết hạn)
            if "feed" in driver.current_url.lower():
                print(f"SUCCESS: Đăng nhập Cookie thành công! Tiêu đề: {driver.current_url.lower()}")
                return True
            else:
                print("WARNING: Cookie không hiệu lực (có thể đã hết hạn).")
                return False
        except Exception as e:
            print(f"ERROR: Lỗi khi add cookie: {e}")
            return False
    else:
        print("ERROR: Không tìm thấy biến môi trường LINKEDIN_COOKIE")
        return False

def save_credentials(username, password):
    """Lưu thông tin đăng nhập vào file"""
    with open(CREDENTIALS_FILE, "wb") as f:
        pickle.dump({"username": username, "password": password}, f)

def handle_cookie_acceptance(driver: webdriver.Chrome):
    """Xử lý chấp nhận cookies nếu có"""
    try:
        driver.find_element(By.XPATH, "//button[span[text()='Accept']]").click()
        print("INFO: COOKIES IS ACCEPTED!")
    except:
        print("INFO: COOKIES IS NOT REQUIRED!")

def handle_code_verification(driver: webdriver.Chrome):
    try:        
        # FIND VERIFICATION FIELD.
        ID_FIELD = "input__email_verification_pin"
        CONDITION = EC.presence_of_element_located((By.ID, ID_FIELD))
        verification_field = WebDriverWait(driver, 20).until(CONDITION)
        # FIND SUBMIT BUTTON.
        ID_FIELD = "email-pin-submit-button"
        CONDITION = EC.presence_of_element_located((By.ID, ID_FIELD))
        submit_button = WebDriverWait(driver, 20).until(CONDITION)
        # ENTER VERIFICATION CODE.
        code = get_missive_linkedin_code()#input("Verification code required! Check your email and enter the code: ")
        print(code)
        time.sleep(2)
        verification_field.send_keys(code)
        time.sleep(3)
        submit_button.click()
        time.sleep(5)
    except Exception as e:
        print("INFO: NO VERIFICATION DETECTED!")
        print(e)

def login(driver: webdriver.Chrome, username: str, password: str):
    """Đăng nhập vào LinkedIn với username và password mới nếu có sự thay đổi"""
    XPATH_USERNAME = '//*[@id="username"]'
    XPATH_PASSWORD = '//*[@id="password"]'
    XPATH_LOGIN_BUTTON = '//button[contains(@class, "btn__primary--large") and @aria-label="Sign in"]'

    driver.get("https://www.linkedin.com/login")
    time.sleep(2)  # Ensure the page is fully loaded

    if os.path.exists(COOKIES_FILE):# and credentials:
        # Kiểm tra nếu username hoặc password đã thay đổi
        #if credentials['username'] == username and credentials['password'] == password:
            # Tải cookies và thử đăng nhập
        load_cookies(driver, COOKIES_FILE)
        driver.get("https://www.linkedin.com/feed")
        time.sleep(3)

        # Kiểm tra xem đã đăng nhập chưa bằng cách xem có biểu tượng người dùng không
        try:
            user_icon = WebDriverWait(driver, 10).until(
                EC.presence_of_element_located((By.CLASS_NAME, 'global-nav__me-photo')))
            print("INFO: Logged in using cookies!")
            driver.save_screenshot("cookie-login.png")
            # save user_icon
            #user_icon.screenshot("user_icon.png")
            # display_screenshot(driver, "status.png")
            return
        except:
            print("INFO: Cookies không hợp lệ, thử đăng nhập lại...")

    # Nếu thông tin đăng nhập đã thay đổi hoặc không có cookies, đăng nhập thủ công
    driver.get("https://www.linkedin.com/login")
    driver.save_screenshot("before_input.png")
    username_field = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_USERNAME)))
    password_field = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_PASSWORD)))
    
    
    human_type(username_field, username)
    #username_field.send_keys(username)
    time.sleep(2)
    human_type(password_field, password)
    #password_field.send_keys(password)
    time.sleep(2)
    for i in range(5):
        try:
            WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, XPATH_LOGIN_BUTTON))).click()
            print(f"Click login thành công ở lần {i+1}")
            break
        except Exception as e:
            print(f"STALE ERROR {i+1}: {e}")
            time.sleep(1)
    
    
    time.sleep(10)
    driver.save_screenshot("before_verification.png")
    handle_code_verification(driver)
    handle_cookie_acceptance(driver)
    # Lưu cookies và thông tin đăng nhập sau khi đăng nhập thành công
    save_cookies(driver)
    #save_credentials(username, password)
    print("INFO: Đăng nhập thành công và đã lưu cookies, thông tin đăng nhập!")
    driver.save_screenshot("post-login.png")


"""# **XPATH**"""

# XPATH ỨNG VỚI NÚT CONNECT.
XPATH_MAIN_CONNECT = (
            # "//main//a[contains(@class, 'profile-top-card')]//button[contains(@aria-label, 'to connect')]"
            # "| //main//a[contains(@class, 'profile-top-card')]//a[contains(@aria-label, 'to connect')]"
            "/html/body/div/div[2]/div[2]/div[2]/div/main/div/div/div[1]/div/div/div[1]/div/section/div/div/div[2]/div[3]/div/div/div[1]/div/div/a"
            "| /html/body/div[6]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/button[contains(@aria-label, 'to connect')]"
            "| //main//button[./span[text()='Connect']]"
            "| //main//a[contains(., 'Connect')]"
        )

# XPATH ỨNG VỚI NÚT MESSAGE.
STATUS_MESSAGE = "/html/body/div/div[2]/div[2]/div[2]/div/main/div/div/div[1]/div/div/div[1]/div/div/section/div/div/div[2]/div[3]/div/div/div[1]/a"#"/html/body/div/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[1]/button"
# XPATH ỨNG VỚI NÚT MORE.
XPATH_MORE_BTN_MAIN = "//main//button[contains(@aria-label, 'More')]"

# XPATH ỨNG VỚI NÚT UNCONNECT KHI NHẤN NÚT MORE.
XPATH_MORE_CONNECT = "/html/body/div[2]/div/div/div[3]/div/div/a | /html/body/div[2]/div/div/div[3]/div/div/button[contains(@aria-label, 'to connect')] | /html/body/div[5]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[2]/div/div/ul/li[3]/div[contains(@aria-label, 'to connect')] | /html/body/div[6]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[2]/div/div/ul/li[3]/div[contains(@aria-label, 'to connect')]" #Đổi sang full XPATH (dễ lỗi hơn nếu có updated từ linkedin)

# XPATH để tìm nút Connected hoặc trạng thái đã kết nối ở màn hình chính
XPATH_CONNECTED_MAIN = "//main//button[contains(., 'Connected')] | //main//div[contains(@aria-label, 'Connected')]"

# XPATH tìm nút Remove Connection bên trong menu More
XPATH_MORE_REMOVE_CONNECTION = "/html/body/div[2]/div/div/div[6]/div/div/div/div/div/p"

# ========================== XPATH/SCRIPT ỨNG VỚI CÁC NÚT ADD EMAIL_NOTE ==========================
#XPATH_BUTTON_ADD_NOTE = "/html/body/div[3]/div/div/div[3]/button[1]"

#XPATH_NOTE_LABEL = "/html/body/div/div[4]//div/div[1]/div/div/div[2]/label"
XPATH_NOTE_LABEL =  """
            function findLabelByText(text) {
                // Hàm này sẽ quét xuyên qua cả Shadow DOM nếu cần
                function search(root) {
                    const labels = root.querySelectorAll('label');
                    for (const lb of labels) {
                        if (lb.textContent.includes(text)) return lb;
                    }
                    
                    // Tìm tiếp trong các shadowRoot khác
                    const all = root.querySelectorAll('*');
                    for (const el of all) {
                        if (el.shadowRoot) {
                            const found = search(el.shadowRoot);
                            if (found) return found;
                        }
                    }
                    return null;
                }
                return search(document);
            }
            return findLabelByText('To verify this member');
            """


# XPATH ỨNG VỚI KHUNG NHẬP NOTE.
# TEXTAREA_NOTE = [
#     "/html/body/div[3]/div/div/div[3]/div[1]/textarea",         # NORMAL ACCOUNT.
#     "/html/body/div[3]/div/div/div[2]/div[2]/div[1]/textarea"   # PREMIUM ACCOUNT.
# ]
# XPATH ỨNG VỚI NÚT GỬI NOTE.
BUTTON_SEND_NOTE = [
    "/html/body/div[3]/div/div/div[4]/button[2]",               # NORMAL ACCOUNT.
    "/html/body/div[3]/div/div/div[3]/button[3]"                # PREMIUM ACCOUNT.
]
# XPATH ỨNG VỚI NÚT GỬI CONNECT MÀ KHÔNG DÙNG NOTE.
# XPATH_SEND_WITHOUT_NOTE = ".//button[contains(@aria-label, 'without a note')]"#"//button[contains(., 'Send without a note') or contains(@aria-label, 'Send without a note') or contains(., 'Send now')]"
# XPATH_SEND_BACKUP = ".//span[contains(normalize-space(), 'without a note')]/parent::button"
# XPATH ỨNG VỚI NÚT GỬI CONNECT MÀ DÙNG NOTE.

#TEXTFIELD_VERIFY_NOTE = "//div[3]//input[@type='email'] | //div[4]//input[@type='email']"#"/html/body/div[3]/div/div/div[2]/label/input[contains(@name, 'email') and contains(@type, 'email)] | /html/body/div[4]/div/div/div[2]/label/input[contains(@name, 'email') and contains(@type, 'email)]"
TEXTFIELD_VERIFY_NOTE  = """
function findElementInShadows(selector) {
    // Hàm tìm kiếm đệ quy xuyên qua các tầng Shadow DOM
    function search(root) {
        // Kiểm tra trong root hiện tại (có thể là document hoặc một shadowRoot)
        const el = root.querySelector(selector);
        if (el) return el;

        // Nếu không thấy, tìm tất cả các phần tử có shadowRoot để quét tiếp
        const allElements = root.querySelectorAll('*');
        for (const element of allElements) {
            if (element.shadowRoot) {
                const found = search(element.shadowRoot);
                if (found) return found;
            }
        }
        return null;
    }
    return search(document);
}

return findElementInShadows('input[name="email"][type="email"]');
"""

# XPATH để nhận diện xem Modal "Add a note" có đang hiển thị hay không
# XPATH_MODAL_TITLE = "//h2[contains(., 'Add a note')]"

"""# **HÀM GỬI KẾT NỐI**"""

def check_status(driver: webdriver.Chrome, xpath: str, *kws):
    try:
        status = driver.find_element(By.XPATH, xpath)
        status_text = status.get_attribute("aria-label")
        if status_text:  # Kiểm tra nếu status_text tồn tại
            for keyword in kws:
                if keyword in status_text:
                    return True
    except NoSuchElementException:
        print(f"Element not found: {xpath}")
    except Exception as e:
        print(f"An error occurred: {e}")
    return False


def find_element_in_list(driver: webdriver.Chrome, e_list: list[str]):
    for e in e_list:
        try:
            return WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, e)))
        except TimeoutException:
            print(f"Timeout for element: {e}")
        except Exception as e:
            print(f"An error occurred: {e}")
    return None
def press_space_with_backup(sleep_time, actions, driver):
    # 1. Thử dùng ActionChains với phím
    actions.send_keys(Keys.SPACE).perform()
    time.sleep(sleep_time)
    
    # 2. KIỂM TRA: Nếu Modal vẫn còn đó, nghĩa là thất bại
    #dùng JavaScript để quét và ép Click vào nút "Send"
    print("⚠️ Phím SPACE/ENTER không tác dụng, kích hoạt Backup: JavaScript Force Click...")
    
    script_click = """
    var buttons = document.querySelectorAll('button');
    var target = Array.from(buttons).find(b => 
        b.innerText.includes('Send without a note') || 
        b.innerText.includes('Send now') || 
        (b.getAttribute('aria-label') && b.getAttribute('aria-label').includes('without a note'))
    );
    if (target) {
        target.click();
        return true;
    }
    return false;
    """
    
    success = driver.execute_script(script_click)
    return success

def send_connection(driver: webdriver.Chrome, profile_mail: str):
    try:
        wait = WebDriverWait(driver, 10)
        actions = webdriver.ActionChains(driver)
        connect_btn = None

        # Bước 1: Tìm nút Connect bên ngoài        
        try:
            connect_btn = wait.until(EC.element_to_be_clickable((By.XPATH, XPATH_CONNECTED_MAIN)))
            print(f"✅ Tìm thấy nút Connect từ ngoài: {connect_btn.tag_name}, {connect_btn.text}")
        except TimeoutException:
            print("🔍 Không thấy nút bên ngoài, thử tìm trong More...")

        # Bước 2: Nếu không thấy, tìm trong More
        if not connect_btn:
            try:
                more_btn = wait.until(EC.element_to_be_clickable((By.XPATH, XPATH_MORE_BTN_MAIN)))
                driver.execute_script("arguments[0].click();", more_btn) #Thay đổi thành arguments[0]
                print("Đã ấn More")
                time.sleep(2)
                print(f"Start finding {XPATH_MORE_CONNECT}")
                connect_btn = wait.until(EC.element_to_be_clickable((By.XPATH, XPATH_MORE_CONNECT)))
                print(f"✅ Tìm thấy nút Connect/Pending trong More: {connect_btn.tag_name}, {connect_btn.text}, {connect_btn.get_attribute('aria-label')}")
                if connect_btn.text == "Pending":
                    print("🔄 Nút đang chờ xác nhận (Pending).")
                    return "ALREADY PENDED"                
            except TimeoutException:
                print("❌ Không tìm thấy nút Connect ở bất cứ đâu, bắt đầu dùng actionChains.")
                #Dùng biện pháp cuối với actionChains
                try:
                    press_multiple_tab(actions, 3, random.uniform(0.25, 0.5))
                    cur_element = driver.switch_to.active_element.text
                    print(f"Current element text: {cur_element}")
                    if cur_element != "Connect" and cur_element != "Invite":
                        actions.send_keys(Keys.TAB).perform()
                        time.sleep(random.uniform(0.25, 0.3))
                    # actions.send_keys(Keys.SPACE).perform()
                    # time.sleep(1)
                    success = press_space_with_backup(2, actions, driver)
                    if success:
                        print("🚀 JavaScript đã ép gửi thành công!")
                    else:
                        # Nếu không tìm thấy nút bằng text, thử click vào phần tử đang focus
                        print("🔍 Thử click vào active_element hiện tại...")
                        driver.execute_script("arguments[0].click();", driver.switch_to.active_element)
                    #Đi vào Modal xác nhận
                    press_multiple_tab(actions, 3, 0.5)
                    # actions.send_keys(Keys.SPACE).perform()
                    # time.sleep(2)
                    # print("🚀 Đã gửi yêu cầu kết nối thành công!")
                    # return "START PENDING"
                    success = press_space_with_backup(2, actions, driver)
                    if success:
                        print("🚀 JavaScript đã ép gửi thành công!")
                        return "START PENDING"
                    else:
                        # Nếu không tìm thấy nút bằng text, thử click vào phần tử đang focus
                        print("🔍 Thử click vào active_element hiện tại...")
                        driver.execute_script("arguments[0].click();", driver.switch_to.active_element)
                        return "START PENDING"    
                except Exception as e:
                    print(f"❌ Lỗi tại actionChains: {str(e)}")
                    return "FAILED"

        # Bước 3: Click vào nút Connect
        driver.execute_script("arguments[0].click();", connect_btn) #Thay đổi thành arguments[0]
        print("🖱️ Đã Click nút Connect. Đang đợi Modal...")
        time.sleep(5) # Đợi popup hiện ra

        # Bước 4.1: Xử lý Modal gửi kết nối khi cần mail note xác thực (Thao tác phím để tránh lỗi XPath popup)
        try:
            # label_note = wait.until(EC.presence_of_element_located((By.XPATH, XPATH_NOTE_LABEL)))            
            label_note = driver.execute_script(XPATH_NOTE_LABEL)
            print(f"Tìm thấy label note: {label_note.tag_name} | {label_note.text} | {label_note.aria_role}")
            #Thử với actionChains
            press_multiple_tab(actions, 3, 0.5) #vào ô popup -> vào learnmore -> vào ô nhập
            actions.send_keys(profile_mail).perform()
            time.sleep(2)
            press_multiple_tab(actions, 2, 0.5) #vào nút "Send a note" -> Vào nút "Send without a note"
            actions.send_keys(Keys.SPACE).perform()
            time.sleep(2)
            return "START PENDING"
            # try:
            #     #driver.execute_script("arguments[0].click();", driver.find_element(By.XPATH, TEXTFIELD_VERIFY_NOTE))
            #     textfield_note = driver.execute_script(TEXTFIELD_VERIFY_NOTE)
            #     driver.execute_script("arguments[0].click();", textfield_note)
            #     print(f"Tìm thấy ô nhập note xác thực email: {driver.switch_to.active_element.tag_name}, đã click vào ô nhập.")
            #     if profile_mail != "":
            #         actions.send_keys(profile_mail).perform()
            #         time.sleep(2)
            #         try:
            #             wait.until(EC.element_to_be_clickable((By.XPATH, BUTTON_SEND_NOTE[0]))).click()
            #             print(f"🚀 Đã gửi yêu cầu kết nối thành công với note xác thực email: {profile_mail}!")
            #             time.sleep(3)
            #         except Exception as e:
            #             print(f"Không tìm thấy nút gửi ghi chú: {str(e)}, tiến hành Actionchains để gửi")
            #             press_multiple_tab(actions, 2, 0.5)
            #             actions.send_keys(Keys.SPACE).perform()
            #             time.sleep(3)
            #             return "START PENDING"
            #     else:
            #         print(f"Không tìm thấy email xác thực: {profile_mail}.")
            #         return "FAILED"
            # except Exception as e:
            #     print(f"❌ Lỗi khi click vào nút textfield ghi chú: {str(e)}, bắt đầu dùng ActionChains")
            #     press_multiple_tab(actions, 3, 0.5)
            #     print(f"Đi đến ô nhập mail: {driver.switch_to.active_element.tag_name} - {driver.switch_to.active_element.aria_role}.")
            #     actions.send_keys(profile_mail).perform()
            #     time.sleep(2)
            #     press_multiple_tab(actions, 2, 0.5)
            #     actions.send_keys(Keys.SPACE).perform()
            #     time.sleep(3)
            #     return "START PENDING"
            
        except Exception as e:
            print(f"Không tìm thấy Modal mail note xác thực: {e}, vào bước 4.2")
            # Bước 4.2: Xử lý Modal gửi kết nối khi không cần mail note xác thực (Thao tác phím để tránh lỗi XPath popup) 
            press_multiple_tab(actions, 3, 0.5)
            actions.send_keys(Keys.SPACE).perform()
            print("🚀 Đã gửi yêu cầu kết nối thành công!")
            time.sleep(2)
            actions.send_keys(Keys.ESCAPE).perform()
            return "START PENDING"                
        
                
    except Exception as e:
        print(f"❌ Lỗi tại send_connection: {str(e)}")
        actions.send_keys(Keys.ESCAPE).perform()
        return "FAILED"
    
def check_connection(driver: webdriver.Chrome, profile_mail: str = ""):
    try:
        # Sử dụng find_elements (số nhiều) để không bị crash nếu không tìm thấy
        # Chỉ kiểm tra nhanh trong 2-3 giây
        pending_elements = driver.find_elements(By.XPATH, "//button[contains(., 'Pending') or contains(., 'Withdraw') or contains(@aria-label, 'Pending') or contains(@aria-label, 'Withdraw')] | /html/body/div/div[2]/div[2]/div[2]/div/main/div/div/div[1]/div/div/div[1]/div/section/div/div/div[2]/div[3]/div/div/div[2]/div/div/a[contains(., 'Pending') or contains(., 'Withdraw')]")
        
        #1 Check có nút Pending
        if len(pending_elements) > 0:
            print("Trạng thái: Đang chờ xác nhận (Pending).")
            return "ALREADY PENDED"
        #2 Check nút Connected ngoài
        connected_main = driver.find_elements(By.XPATH, XPATH_CONNECTED_MAIN)
        if len(connected_main) > 0:
            print(f"Trạng thái: Đã kết nối (Tìm thấy nút Connected ngoài): {connected_main}")
            return "CONNECTED"
        else:
            print("Không tìm thấy nút Connected ngoài.")

        #3 Check nút "Remove connection" bên trong menu "More"
        try:
            print(f"Start finding {XPATH_MORE_BTN_MAIN}")
            more_btn = WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, XPATH_MORE_BTN_MAIN)))
            driver.execute_script("arguments[0].click();", more_btn)
            time.sleep(2)
            
            remove_btn = driver.find_elements(By.XPATH, XPATH_MORE_REMOVE_CONNECTION)
            if len(remove_btn) > 0:
                print(f"🔍 Trạng thái: Đã kết nối (Tìm thấy Remove connection trong More): {remove_btn}")
                # Đóng menu More trước khi thoát
                webdriver.ActionChains(driver).send_keys(Keys.ESCAPE).perform()
                return "CONNECTED"
            
            # Nếu không thấy nút Remove, đóng menu More để tiếp tục tìm Connect
            print("Không tìm thấy nút Remove connection trong More, sẽ thử gửi kết nối nếu có thể.")
            webdriver.ActionChains(driver).send_keys(Keys.ESCAPE).perform()
            time.sleep(1)
        except:
            pass
        
        # Nếu không phải Pending hoặc chưa CONNECTED hoặc chưa có nút "Remove Connection" trong More, mới tiến hành gửi connection
        print("Trạng thái: Chưa gửi, bắt đầu gọi send_connection...")
        res = send_connection(driver, profile_mail)
        return res

    except Exception as e:
        print(f"❌ Lỗi tại check_connection: {str(e)}")
        return f"ERROR: {str(e)}"
        
def main_connect():
    #restore_cookie_from_secret()
    
    # 1. ĐỌC DỮ LIỆU ĐẢM BẢO KHÔNG THIẾU DÒNG/CỘT
    result = sheet.values().get(spreadsheetId=SPREADSHEET_ID, range=RANGE_NAME).execute()
    values = result.get('values', [])
    
    if not values:
        print("ERROR: Không có dữ liệu trong Sheet")
        return
    headers = values[0]
    required_min_cols = 5 
    if len(headers) < required_min_cols:
        headers += [f"Column_{i}" for i in range(len(headers), required_min_cols)]

    data = []
    for row in values[1:]:
        # Làm đầy dòng để khớp với số lượng headers mới
        padded_row = row + [""] * (len(headers) - len(row))
        data.append(padded_row)
        
    df = pd.DataFrame(data, columns=headers)

    # 2. KHỞI TẠO DRIVER & ĐĂNG NHẬP
    driver = get_driver()
    COL_DROPDOWN = "Trạng thái kết nối (đôi khi nút Connect nằm trong nút More)"
    COL_STATUS = "STATUS"
    
    username = os.getenv("LINKEDIN_USERNAME")
    password = os.getenv("LINKEDIN_PASSWORD")
    login(driver, username, password)

    send_count = 0

    # 3. VÒNG LẶP XỬ LÝ
    for index, row in df.iterrows():
        print("===========================START==================================")
        if send_count >= MAX_LIMIT:
            break
        profile_link = str(row.iloc[0]).strip()
        profile_mail = str(row.iloc[1]).strip()
        current_status_text = str(row.iloc[3]).strip().upper()
        current_dropdown = str(row.iloc[2]).strip().lower()

        # Kiểm tra nếu dòng này rỗng hoàn toàn (không có link) thì bỏ qua
        if not profile_link or "linkedin.com" not in profile_link:
            continue

        # LOGIC SKIP: Chỉ chạy nếu chưa gửi connect và chưa là bạn bè
        # Chấp nhận các ô trống hoặc giá trị nan
        is_processed = current_dropdown != "" and current_dropdown != "nan"
        is_connected = current_status_text in ["CONNECTED", "PENDING"]

        if is_processed or is_connected:
            print(f"⏭️ Bỏ qua dòng {index + 2}: {profile_link} (Trạng thái: {current_dropdown})")
            continue

        # THỰC HIỆN KẾT NỐI
        print(f"🚀 Đang xử lý dòng {index + 2}: {profile_link}")
        try:
            driver.get(profile_link)
            #trả về 404 page not found thì bỏ qua            
            time.sleep(random.uniform(5, 6))
            if driver.current_url == "https://www.linkedin.com/404/":
                print(f"⏭️ Bỏ qua dòng {index + 2}: {profile_link} (Trạng thái: 404 Not Found)")
                continue
            driver.save_screenshot(f"before_check_index{index}.png")
            # Kiểm tra và gửi connect
            #email_to_fill = row.get("Email để điền khi gặp câu hỏi trog lúc connect", "")
            status = check_connection(driver, profile_mail)
            
            # Cập nhật DataFrame
            #df.at[index, COL_STATUS] = status
            df.iat[index, 3] = status
            if status in ["SUCCESS", "START PENDING", "SUCCESS: CONNECT WITHOUT NOTE!", "PENDING"]:
                #df.at[index, COL_DROPDOWN] = "Đã gửi connect"
                df.iat[index, 2] = "Đã gửi connect"
                send_count += 1
                driver.save_screenshot(f"success_sent_index{index}_count{send_count}.png")
            
            # Nghỉ để tránh bị quét bot
            time.sleep(random.uniform(15, 25))
            
        except Exception as e:
            print(f"❌ Lỗi dòng {index + 2}: {e}")
            driver.save_screenshot(f"fail_sent_index{index}_count{send_count}.png")
            df.at[index, COL_STATUS] = "ERROR"

    # 4. CẬP NHẬT LẠI GOOGLE SHEETS DÙNG BATCH UPDATE
    print("📤 Đang chuẩn bị dữ liệu Batch Update...")
    
    df_to_upload = df.fillna("") 
    final_values = df_to_upload.values.tolist()
    
    num_rows = len(final_values)
    num_cols = len(df_to_upload.columns)
    last_col_letter = chr(ord('A') + num_cols - 1)
    
    # Định nghĩa vùng dữ liệu (Data Range)
    update_range = f"Sheet1!A2:{last_col_letter}{num_rows + 1}"

    # Cấu trúc body cho batchUpdate
    batch_update_values_request_body = {
        'valueInputOption': 'RAW',
        'data': [
            {
                'range': update_range,
                'values': final_values
            }
        ]
    }

    try:
        # Sử dụng batchUpdate thay vì update thông thường
        service.spreadsheets().values().batchUpdate(
            spreadsheetId=SPREADSHEET_ID,
            body=batch_update_values_request_body
        ).execute()
        print(f"✅ Batch Update thành công vùng {update_range}!")
    except Exception as e:
        print(f"❌ Lỗi Batch Update: {e}")
        # Backup plan: Nếu batch vẫn lỗi SSL, chia nhỏ để gửi (Chunking)
        print("🔄 Đang thử gửi lại theo phương thức Chia nhỏ (Chunking)...")
        chunk_size = 5
        for i in range(0, len(final_values), chunk_size):
            chunk = final_values[i : i + chunk_size]
            r_start = i + 2
            r_end = r_start + len(chunk) - 1
            c_range = f"Sheet1!A{r_start}:{last_col_letter}{r_end}"
            service.spreadsheets().values().update(
                spreadsheetId=SPREADSHEET_ID,
                range=c_range,
                valueInputOption='RAW',
                body={'values': chunk}
            ).execute()
            
    driver.quit()
    print("Đã thoát")
