# -*- coding: utf-8 -*-
"""Copy of Connect Linkedin with cookie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbFI1QUjPJiU3kliY8qOVLAp36kJ1kUb

# **CÀI ĐẶT THƯ VIỆN CẦN THIẾT**
"""



import os
import undetected_chromedriver as uc
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from dotenv import load_dotenv
import pickle
# === GOOGLE SHEETS LOCAL SETUP ===
import pandas as pd
from googleapiclient.discovery import build
from google.oauth2 import service_account
from googleapiclient.errors import HttpError
# === GOOGLE SHEETS LOCAL SETUP ===
import random
import json
import requests
import pandas as pd
from googleapiclient.discovery import build
from google.oauth2 import service_account
# === FastAPI API ===

load_dotenv(override=True)

# --- CONFIG ---
MISSIVE_API_KEY = os.getenv('MISSIVE_API_KEY')
HEADERS = {"Authorization": f"Bearer {MISSIVE_API_KEY}", "Content-Type": "application/json"}
PARAMS = {"limit": 20, "inbox":"true"} 
COOKIES_FILE = 'linkedin_cookies.pkl'
CREDENTIALS_FILE = 'linkedin_credentials.pkl'
MAX_LIMIT = 15
SPREADSHEET_ID = os.getenv('SPREADSHEET_ID')
RANGE_NAME = "Sheet1!A:E"
GOOGLE_CREDS = os.getenv('GOOGLE_APPLICATION_CRED')
TARGET_URL = "https://www.linkedin.com/uas/login?session_redirect=https%3A%2F%2Fwww.linkedin.com%2Ffeed%2F"

"""# **XPATH**"""

# XPATH ỨNG VỚI NÚT CONNECT.
# XPATH_MAIN_CONNECT = """
# return document.evaluate(
#     "/html/body/div/div/div/div/div/main/div/div/div/div/div/div/div/section/div/div/div/div/div/div/div/div/div/a | /html/body/div/div/div/div/div/div/div/main/section/div/div/div/button[contains(@aria-label, 'to connect')] | //main//button[./span[text()='Connect']] | //main//a[contains(., 'Connect')]", 
#     document, 
#     null, 
#     XPathResult.FIRST_ORDERED_NODE_TYPE, 
#     null
# ).singleNodeValue;
# """
# Login fields/buttons
XPATH_USERNAME = '//*[@id="username"]'# | //input[@id=":r3:"] | //input[contains(@id, "r")] | //input[@autocomplete="username" or @autocomplete="webauthn"]'
XPATH_PASSWORD = '//*[@id="password"]'# | //input[@id=":r4:"] | //input[contains(@id, "r")] | //input[@autocomplete="current-password"]'
XPATH_LOGIN_BUTTON = '//button[contains(@class, "btn__primary--large") and @aria-label="Sign in"]'# | //button[.//text()[contains(., "Sign in") or contains(., "Log in") or contains(., "Đăng nhập")]]'

XPATH_MAIN_CONNECT = (
            # "//main//a[contains(@class, 'profile-top-card')]//button[contains(@aria-label, 'to connect')]"
            # "| //main//a[contains(@class, 'profile-top-card')]//a[contains(@aria-label, 'to connect')]"
            "/html/body/div/div[2]/div[2]/div[2]/div/main/div/div/div[1]/div/div/div[1]/div/section/div/div/div[2]/div[3]/div/div/div[1]/div/div/a"
            "| /html/body/div[6]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/button[contains(@aria-label, 'to connect')]"
            "| //main//button[./span[text()='Connect']]"
            "| //main//a[contains(., 'Connect')]"
        )
XPATH_FAILED_ALERT_POPUP = "/html/body/div/section/div[1]/div/div[1]/div/div/p[contains(text(), 'try again') or contains(text(), 'can resend')] | /html/body/div/section/div/div/div/div/div/p[contains(text(), 'try again') or contains(text(), 'can resend')]"
XPATH_PENDING_BUTTON = "/html/body/div/div[2]/div[2]/div[2]/div/main/div/div/div[1]/div/div/div[1]/div/div/section/div/div/div[2]/div[3]/div/div/div[2]/div/div/a/span/span[text()='Pending'] | /html/body/div/div[2]/div[2]/div[2]/div/main/div/div/div[1]/div/div/div[1]/div/section/div/div/div[2]/div[3]/div/div/div[2]/div/div/a[contains(@aria-label, 'to withdraw')]"
# XPATH ỨNG VỚI NÚT MESSAGE.
STATUS_MESSAGE = "/html/body/div/div[2]/div[2]/div[2]/div/main/div/div/div[1]/div/div/div[1]/div/div/section/div/div/div[2]/div[3]/div/div/div[1]/a"#"/html/body/div/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[1]/button"
# XPATH ỨNG VỚI NÚT MORE.
XPATH_MORE_BTN_MAIN = "//main//button[contains(@aria-label, 'More')] | //main//a[contains(@aria-label, 'More')] | //main//button//span[contains(text(), 'More')] | /html/body/div/div[2]/div[2]/div[2]/div/main/div/div/div[1]/div/div/div[1]/div/section/div/div/div[2]/div[3]/div/div/div[3]/button/span/span[contains(text(), 'More')] | /html/body/div[1]/div[2]/div[2]/div[2]/div/main/div/div/div[1]/div/div/div[1]/div/section/div/div/div[2]/div[3]/div/div/div[3]/button/span/span[contains(text(), 'More')]"

# XPATH ỨNG VỚI NÚT UNCONNECT KHI NHẤN NÚT MORE.
XPATH_MORE_CONNECT = "/html/body/div[2]/div/div/div[3]/div/div/a | /html/body/div[2]/div/div/div[3]/div/div/button[contains(@aria-label, 'to connect')] | /html/body/div[5]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[2]/div/div/ul/li[3]/div[contains(@aria-label, 'to connect')] | /html/body/div[6]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[2]/div/div/ul/li[3]/div[contains(@aria-label, 'to connect')] | /html/body/div[2]/div/div/div[3]/div/div/div/div[contains(@aria-label, 'to connect')]" #Đổi sang full XPATH (dễ lỗi hơn nếu có updated từ linkedin)

# XPATH tìm nút Remove Connection bên trong menu More
XPATH_MORE_REMOVE_CONNECTION = "/html/body/div[2]/div/div/div[6]/div/div/div/div/div/p | /html/body/div[6]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[3]/div/div[2]/div/div/ul/li[6]/div"

# ========================== XPATH/SCRIPT ỨNG VỚI CÁC NÚT ADD EMAIL_NOTE ==========================
#XPATH_BUTTON_ADD_NOTE = "/html/body/div[3]/div/div/div[3]/button[1]"

#XPATH_NOTE_LABEL = "/html/body/div/div[4]//div/div[1]/div/div/div[2]/label"
XPATH_NOTE_LABEL =  """
            function findLabelByText(text) {
                // Hàm này sẽ quét xuyên qua cả Shadow DOM nếu cần
                function search(root) {
                    const labels = root.querySelectorAll('label');
                    for (const lb of labels) {
                        if (lb.textContent.includes(text)) return lb;
                    }
                    
                    // Tìm tiếp trong các shadowRoot khác
                    const all = root.querySelectorAll('*');
                    for (const el of all) {
                        if (el.shadowRoot) {
                            const found = search(el.shadowRoot);
                            if (found) return found;
                        }
                    }
                    return null;
                }
                return search(document);
            }
            return findLabelByText('To verify this member');
            """


# XPATH ỨNG VỚI KHUNG NHẬP NOTE.
# TEXTAREA_NOTE = [
#     "/html/body/div[3]/div/div/div[3]/div[1]/textarea",         # NORMAL ACCOUNT.
#     "/html/body/div[3]/div/div/div[2]/div[2]/div[1]/textarea"   # PREMIUM ACCOUNT.
# ]
# XPATH ỨNG VỚI NÚT GỬI NOTE.
BUTTON_SEND_NOTE = [
    "/html/body/div[3]/div/div/div[4]/button[2]",               # NORMAL ACCOUNT.
    "/html/body/div[3]/div/div/div[3]/button[3]"                # PREMIUM ACCOUNT.
]
# XPATH ỨNG VỚI NÚT GỬI CONNECT MÀ KHÔNG DÙNG NOTE.
# XPATH_SEND_WITHOUT_NOTE = ".//button[contains(@aria-label, 'without a note')]"#"//button[contains(., 'Send without a note') or contains(@aria-label, 'Send without a note') or contains(., 'Send now')]"
# XPATH_SEND_BACKUP = ".//span[contains(normalize-space(), 'without a note')]/parent::button"
# XPATH ỨNG VỚI NÚT GỬI CONNECT MÀ DÙNG NOTE.

#TEXTFIELD_VERIFY_NOTE = "//div[3]//input[@type='email'] | //div[4]//input[@type='email']"#"/html/body/div[3]/div/div/div[2]/label/input[contains(@name, 'email') and contains(@type, 'email)] | /html/body/div[4]/div/div/div[2]/label/input[contains(@name, 'email') and contains(@type, 'email)]"
TEXTFIELD_VERIFY_NOTE  = """
function findElementInShadows(selector) { 
    // Hàm tìm kiếm đệ quy xuyên qua các tầng Shadow DOM
    function search(root) {
        // Kiểm tra trong root hiện tại (có thể là document hoặc một shadowRoot)
        const el = root.querySelector(selector);
        if (el) return el;

        // Nếu không thấy, tìm tất cả các phần tử có shadowRoot để quét tiếp
        const allElements = root.querySelectorAll('*');
        for (const element of allElements) {
            if (element.shadowRoot) {
                const found = search(element.shadowRoot);
                if (found) return found;
            }
        }
        return null;
    }
    return search(document);
}

return findElementInShadows('input[name="email"][type="email"]');
"""

# XPATH để nhận diện xem Modal "Add a note" có đang hiển thị hay không
# XPATH_MODAL_TITLE = "//h2[contains(., 'Add a note')]"

"""# **HÀM HỖ TRỢ**"""
def human_scroll(driver):
    """Cuộn trang lên xuống ngẫu nhiên để mô phỏng người đọc profile"""
    total_height = driver.execute_script("return document.body.scrollHeight")
    scroll_point = random.randint(300, 700)
    driver.execute_script(f"window.scrollTo(0, {scroll_point});")
    time.sleep(random.uniform(1, 2))
    driver.execute_script(f"window.scrollTo({scroll_point}, 0);")
    print("DEBUG: Đã thực hiện cuộn trang giả lập.")

def human_click(driver, element):
    """Click vào một vị trí ngẫu nhiên trên button thay vì chính giữa"""
    try:
        action = ActionChains(driver)
        width = element.size['width']
        height = element.size['height']
        # Lệch ngẫu nhiên trong phạm vi 20% kích thước nút
        offset_x = random.randint(-int(width/5), int(width/5))
        offset_y = random.randint(-int(height/5), int(height/5))
        action.move_to_element_with_offset(element, offset_x, offset_y).click().perform()
    except Exception:
        driver.execute_script("arguments.click();", element)
        
def press_multiple_tab(actions,number_of_presses, wait_time):
    for i in range(number_of_presses):
        actions.send_keys(Keys.TAB).perform()
        time.sleep(wait_time)

def get_missive_linkedin_code():
    response = requests.get("https://public.missiveapp.com/v1/conversations", headers=HEADERS, params=PARAMS)
    if response.status_code != 200:
        return f"Lỗi API: {response.status_code}"
    conversations = response.json().get("conversations", [])
    temp = [c['latest_message_subject'] for c in conversations if 'name' in c['authors'][0] and c['authors'][0]['name'] == 'LinkedIn']
    final_temp = [f.split(' ')[-1:][0] for f in temp]
    for item in final_temp:
        if item.isdigit():
            return item
    return None

        
def human_type(element, text):
    """Gõ phím như người thật với độ trễ ngẫu nhiên"""
    for char in text:
        element.send_keys(char)
        time.sleep(random.uniform(0.1, 0.3))

"""# **KẾT NỐI GOOGLE SHEETS**"""
def execute_with_retry(request, max_retries=5):
    for i in range(max_retries):
        try:
            return request.execute()
        except HttpError as e:
            if e.resp.status in [500, 502, 503, 504] and i < max_retries - 1:
                wait_time = (2 ** i) + random.random()
                print(f"Google Sheets Service quá tải tạm thời (503). Thử lại sau {wait_time:.2f}s...")
                time.sleep(wait_time)
                continue
            raise e
        
def get_gsheet_service():
    scopes = ['https://www.googleapis.com/auth/spreadsheets']
    info = json.loads(GOOGLE_CREDS)
    creds = service_account.Credentials.from_service_account_info(info, scopes=scopes)
    service = build('sheets', 'v4', credentials=creds)
    return service

service = get_gsheet_service()
sheet = service.spreadsheets()
requests_spreadsheet = sheet.values().get(spreadsheetId=SPREADSHEET_ID, range=RANGE_NAME)
result = execute_with_retry(requests_spreadsheet)
values = result.get('values', [])
max_cols = max(len(row) for row in values) if values else 0
values = [row + [''] * (max_cols - len(row)) for row in values]
df = pd.DataFrame(values[1:], columns=values[0] if values else [])
df = df.fillna('')


"""# **CẤU HÌNH DRIVER**"""
# def get_driver():
#     options = webdriver.ChromeOptions()
    
#     # 1. Định nghĩa một User-Agent nhất quán (Tránh khai báo 2 lần)
#     user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
#     options.add_argument(f"user-agent={user_agent}")

#     # 2.1 Các thiết lập cơ bản cho môi trường Linux/Docker (GitHub Actions)
#     options.add_argument('--no-sandbox')
#     options.add_argument("--disable-dev-shm-usage")
#     options.add_argument('--disable-gpu')
#     options.add_argument('--headless=new')
#     options.add_argument("--window-size=1920,1080")
#     options.page_load_strategy = 'eager'
#     # 2.2 Ép trình duyệt và Header luôn yêu cầu tiếng Anh (vài text button không phải tiếng anh)
#     options.add_argument('--lang=en-GB') 
#     options.add_experimental_option('prefs', {'intl.accept_languages': 'en,en_GB'})
    
#     # 3. CHỐNG PHÁT HIỆN BOT (Stealth Mode)
#     # Loại bỏ cờ 'nút điều khiển tự động'
#     options.add_experimental_option("excludeSwitches", ["enable-automation"])
#     options.add_experimental_option('useAutomationExtension', False)
#     # Vô hiệu hóa tính năng AutomationControlled của Blink
#     options.add_argument("--disable-blink-features=AutomationControlled")
    
#     # Thêm các cờ để trình duyệt giống người dùng thật hơn
#     options.add_argument("--disable-infobars")
#     options.add_argument("--disable-notifications")
    
#     # Khởi tạo driver
#     driver = webdriver.Chrome(options=options)
    
#     # 4. Ẩn thuộc tính navigator.webdriver bằng Script thực thi ngay khi load trang
#     driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
#         "source": """
#             Object.defineProperty(navigator, 'webdriver', {
#                 get: () => undefined
#             })
#         """
#     })
    
#     return driver
def get_driver():
    options = uc.ChromeOptions()
    
    # 1. Cấu hình cơ bản cho môi trường Headless (GitHub Actions)
    options.add_argument('--headless=new')
    options.add_argument('--no-sandbox')
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument('--disable-gpu')
    options.add_argument("--window-size=1920,1080")
    
    # 2. [TĂNG TỐC] Chiến lược load trang
    # 'eager' giúp trình duyệt không chờ đợi tải xong ảnh hay script bên thứ 3
    options.page_load_strategy = 'eager'
    
    # 3. [TĂNG TỐC] Chặn tải hình ảnh, CSS và Fonts để tiết kiệm băng thông và RAM
    # prefs = {
    #     "profile.managed_default_content_settings.images": 2,
    #     "profile.managed_default_content_settings.stylesheets": 2,
    #     "profile.managed_default_content_settings.fonts": 2
    # }
    # options.add_experimental_option("prefs", prefs)
    
    # 4. Ép trình duyệt dùng tiếng Anh
    options.add_argument('--lang=en-GB')
    
    # 5. [CHỐNG PHÁT HIỆN] Thêm Proxy dân cư (Khuyến nghị)
    # Trên GitHub Actions, hãy set secrets.PROXY_URL (ví dụ: http://user:pass@ip:port)
    proxy_url = os.getenv("PROXY_URL")
    if proxy_url:
        options.add_argument(f'--proxy-server={proxy_url}')
    
    # Khởi tạo undetected_chromedriver (Không dùng webdriver.Chrome thông thường)
    driver = uc.Chrome(options=options, version_main=146)
    
    # 6. [CHỐNG PHÁT HIỆN] Bơm thêm Stealth Script qua CDP
    driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
        "source": """
            // Ẩn webdriver
            Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
            
            // Fake runtime của Chrome (Bot thường không có cái này)
            window.navigator.chrome = { runtime: {} };
            
            // Bơm thêm plugins giả
            Object.defineProperty(navigator, 'plugins', {
                get: () => [1, 2, 3, 4, 5]
            });
            
            // Ép ngôn ngữ
            Object.defineProperty(navigator, 'languages', {
                get: () => ['en-GB', 'en-US', 'en']
            });
        """
    })
    
    return driver

"""# **HÀM ĐĂNG NHẬP**"""

def save_cookies(driver):
    """Lưu cookies vào file"""
    with open(COOKIES_FILE, "wb") as cookies_file:
        pickle.dump(driver.get_cookies(), cookies_file)
    print("INFO: COOKIES SAVED!")

def load_cookies(driver: webdriver.Chrome, file_name: str):
    """Đọc cookies từ file pickle và thêm vào browser"""
    if os.path.exists(file_name):
        with open(file_name, 'rb') as f:
            cookies = pickle.load(f)
            for cookie in cookies:
                driver.add_cookie(cookie)
                
def login_with_cookie(driver):
    """Xử lý đăng nhập bằng Cookie li_at từ .env"""
    print("INFO: Đang thử đăng nhập bằng Cookie...")
    # Bước 1: Vào domain LinkedIn trước để trình duyệt chấp nhận cookie
    driver.get("https://www.linkedin.com/login")
    time.sleep(3)

    li_at_cookie = os.getenv("LINKEDIN_COOKIE")
    
    if li_at_cookie:
        try:
            driver.delete_all_cookies()
            driver.add_cookie({
                "name": "li_at",
                "value": li_at_cookie,
                "domain": ".linkedin.com",
                "path": "/",
                "secure": True
            })
            
            # Bước 2: Refresh vào trang Feed
            driver.get("https://www.linkedin.com/feed/")
            time.sleep(5)
            
            # Bước 3: Kiểm tra xem đã vào được Feed chưa (tránh trường hợp cookie hết hạn)
            if "feed" in driver.current_url.lower():
                print(f"SUCCESS: Đăng nhập Cookie thành công! Tiêu đề: {driver.current_url.lower()}")
                return True
            else:
                print("WARNING: Cookie không hiệu lực (có thể đã hết hạn).")
                return False
        except Exception as e:
            print(f"ERROR: Lỗi khi add cookie: {e}")
            return False
    else:
        print("ERROR: Không tìm thấy biến môi trường LINKEDIN_COOKIE")
        return False

def save_credentials(username, password):
    """Lưu thông tin đăng nhập vào file"""
    with open(CREDENTIALS_FILE, "wb") as f:
        pickle.dump({"username": username, "password": password}, f)

def handle_cookie_acceptance(driver: webdriver.Chrome):
    """Xử lý chấp nhận cookies nếu có"""
    try:
        driver.find_element(By.XPATH, "//button[span[text()='Accept']]").click()
        print("INFO: COOKIES IS ACCEPTED!")
    except:
        print("INFO: COOKIES IS NOT REQUIRED!")

def handle_code_verification(driver: webdriver.Chrome):
    try:        
        # FIND VERIFICATION FIELD.
        ID_FIELD = "input__email_verification_pin"
        CONDITION = EC.presence_of_element_located((By.ID, ID_FIELD))
        verification_field = WebDriverWait(driver, 20).until(CONDITION)
        # FIND SUBMIT BUTTON.
        ID_FIELD = "email-pin-submit-button"
        CONDITION = EC.presence_of_element_located((By.ID, ID_FIELD))
        submit_button = WebDriverWait(driver, 20).until(CONDITION)
        # ENTER VERIFICATION CODE.
        code = get_missive_linkedin_code()#input("Verification code required! Check your email and enter the code: ")
        print(code)
        time.sleep(2)
        verification_field.send_keys(code)
        time.sleep(3)
        submit_button.click()
        time.sleep(5)
    except Exception as e:
        print("INFO: NO VERIFICATION DETECTED!")
        print(e)

# def login(driver: webdriver.Chrome, username: str, password: str):
#     """Đăng nhập vào LinkedIn với username và password mới nếu có sự thay đổi"""
#     XPATH_USERNAME = '//*[@id="username"]'
#     XPATH_PASSWORD = '//*[@id="password"]'
#     XPATH_LOGIN_BUTTON = '//button[contains(@class, "btn__primary--large") and @aria-label="Sign in"]'

#     driver.get("https://www.linkedin.com/login")
#     time.sleep(2)  # Ensure the page is fully loaded

#     if os.path.exists(COOKIES_FILE):# and credentials:
#         # Kiểm tra nếu username hoặc password đã thay đổi
#         #if credentials['username'] == username and credentials['password'] == password:
#             # Tải cookies và thử đăng nhập
#         load_cookies(driver, COOKIES_FILE)
#         driver.get("https://www.linkedin.com/feed")
#         time.sleep(10)

#         # Kiểm tra xem đã đăng nhập chưa bằng cách xem có biểu tượng người dùng không
#         try:
#             user_icon = WebDriverWait(driver, 20).until(
#                 EC.presence_of_element_located((By.CLASS_NAME, 'global-nav__me-photo')))
#             print("INFO: Đã đăng nhập với cookies!")
#             driver.save_screenshot("cookie-login.png")
#             # save user_icon
#             #user_icon.screenshot("user_icon.png")
#             # display_screenshot(driver, "status.png")
#             return
#         except Exception as e:
#             print(f"INFO: Đăng nhập Cookie không thành công: {e}")
#             os.remove(COOKIES_FILE)
#     else:
#         print("INFO: Không có file cookies")
        
#     print("INFO: Bắt đầu login thủ công")
#     # Nếu thông tin đăng nhập đã thay đổi hoặc không có cookies, đăng nhập thủ công
#     driver.get("https://www.linkedin.com/login")
#     time.sleep(5)
#     if "feed" in driver.current_url.lower():
#         print(f"SUCCESS: Đã tự động vào Feed tại {driver.current_url}. Bỏ qua bước nhập pass.")
#         save_cookies(driver) # Lưu lại cookie mới cho chắc
#         return
    
#     driver.save_screenshot("before_input.png")
#     username_field = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_USERNAME)))
#     password_field = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_PASSWORD)))
    
    
#     human_type(username_field, username)
#     #username_field.send_keys(username)
#     time.sleep(2)
#     human_type(password_field, password)
#     #password_field.send_keys(password)
#     time.sleep(2)
#     for i in range(5):
#         try:
#             WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, XPATH_LOGIN_BUTTON))).click()
#             print(f"Click login thành công ở lần {i+1}")
#             break
#         except Exception as e:
#             print(f"STALE ERROR {i+1}: {e}")
#             time.sleep(1)
    
    
#     time.sleep(15)
#     driver.save_screenshot("before_verification.png")
#     handle_code_verification(driver)
#     handle_cookie_acceptance(driver)
#     # Lưu cookies và thông tin đăng nhập sau khi đăng nhập thành công
#     save_cookies(driver)
#     #save_credentials(username, password)
#     print("INFO: Đăng nhập thành công và đã lưu cookies, thông tin đăng nhập!")
#     driver.save_screenshot("post-login.png")
def login(driver: webdriver.Chrome, username: str, password: str):
    """Đăng nhập vào LinkedIn với username và password mới nếu có sự thay đổi"""
    # Use module-level XPATH constants defined at top

    driver.get(TARGET_URL)
    time.sleep(2)  # Ensure the page is fully loaded
    print(f"URL login: {driver.current_url}")
    # Kiểm tra nếu có cookies và kiểm tra xem username, password có thay đổi không
    #credentials = load_credentials()

    if os.path.exists(COOKIES_FILE):# and credentials:
        # Kiểm tra nếu username hoặc password đã thay đổi
        #if credentials['username'] == username and credentials['password'] == password:
            # Tải cookies và thử đăng nhập
        load_cookies(driver, COOKIES_FILE)
        driver.refresh()
        time.sleep(10)

        # Kiểm tra xem đã đăng nhập chưa bằng cách xem có biểu tượng người dùng không
        # try:
        #     user_icon = WebDriverWait(driver, 20).until(
        #         EC.presence_of_element_located((By.CLASS_NAME, 'global-nav__me-photo')))
        #     print("INFO: Logged in using cookies!")
        #     driver.save_screenshot("cookie-login.png")
        #     # save user_icon
        #     #user_icon.screenshot("user_icon.png")
        #     # display_screenshot(driver, "status.png")
        #     return
        # except Exception as e:
        #     print(f"INFO: Đăng nhập Cookie không thành công: {e}")
        #     os.remove(COOKIES_FILE)
        print(f"Current url: {driver.current_url}")
        if "linkedin.com/login" in driver.current_url or "checkpoint" in driver.current_url:
            print(f"INFO: Đăng nhập Cookie không thành công")
            os.remove(COOKIES_FILE)
        else:
            print("Đăng nhập cookie ok")
            return
    else:
        print("INFO: Không có file cookies")
        
    print("INFO: Bắt đầu login thủ công")
    driver.get("https://www.linkedin.com/login")
    time.sleep(5)
    if "feed" in driver.current_url.lower():
        print(f"SUCCESS: Đã tự động vào Feed tại {driver.current_url}. Bỏ qua bước nhập pass.")
        save_cookies(driver)
        return
    driver.save_screenshot("before_input.png")
    username_field = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_USERNAME)))
    password_field = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_PASSWORD)))
    login_button = WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, XPATH_LOGIN_BUTTON)))
    
    human_type(username_field, username)
    #username_field.send_keys(username)
    time.sleep(2)
    human_type(password_field, password)
    #password_field.send_keys(password)
    time.sleep(2)
    login_button.click()

    time.sleep(30)
    driver.save_screenshot("before_verification.png")
    handle_code_verification(driver)
    handle_cookie_acceptance(driver)
    # Lưu cookies và thông tin đăng nhập sau khi đăng nhập thành công
    save_cookies(driver)
    #save_credentials(username, password)
    print("INFO: Đăng nhập thành công và đã lưu cookies, thông tin đăng nhập!")
    driver.save_screenshot("post-login.png")

"""# **HÀM GỬI KẾT NỐI**"""

def check_status(driver: webdriver.Chrome, xpath: str, *kws):
    try:
        status = driver.find_element(By.XPATH, xpath)
        status_text = status.get_attribute("aria-label")
        if status_text:  # Kiểm tra nếu status_text tồn tại
            for keyword in kws:
                if keyword in status_text:
                    return True
    except NoSuchElementException:
        print(f"Element not found: {xpath}")
    except Exception as e:
        print(f"An error occurred: {e}")
    return False


def find_element_in_list(driver: webdriver.Chrome, e_list: list[str]):
    for e in e_list:
        try:
            return WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, e)))
        except TimeoutException:
            print(f"Timeout for element: {e}")
        except Exception as e:
            print(f"An error occurred: {e}")
    return None
def press_space_with_backup(sleep_time, actions, driver):
    # 1. Thử dùng ActionChains với phím
    actions.send_keys(Keys.SPACE).perform()
    time.sleep(sleep_time)
    
    # 2. KIỂM TRA: Nếu Modal vẫn còn đó, nghĩa là thất bại
    #dùng JavaScript để quét và ép Click vào nút "Send"
    print("⚠️ Phím SPACE/ENTER không tác dụng, kích hoạt Backup: JavaScript Force Click...")
    
    script_click = """
    var buttons = document.querySelectorAll('button');
    var target = Array.from(buttons).find(b => 
        b.innerText.includes('Send without a note') || 
        b.innerText.includes('Send now') || 
        (b.getAttribute('aria-label') && b.getAttribute('aria-label').includes('without a note'))
    );
    if (target) {
        target.click();
        return true;
    }
    return false;
    """
    
    success = driver.execute_script(script_click)
    return success

def send_connection(driver: webdriver.Chrome, profile_mail: str):
    try:
        wait = WebDriverWait(driver, 10)
        actions = webdriver.ActionChains(driver)
        connect_btn = None

        try:
            # Bước 1: Tìm nút Connect bên ngoài        
            connect_btn = wait.until(EC.element_to_be_clickable((By.XPATH, XPATH_MAIN_CONNECT)))
            print(f"✅ Tìm thấy nút Connect từ ngoài: {connect_btn.tag_name}, {connect_btn.text}")
            driver.execute_script("arguments[0].click();", connect_btn) #Thay đổi thành arguments[0]
        except:
            print("🔍 Không thấy nút bên ngoài, thử tìm trong More...")
        # Bước 2: Nếu không thấy, tìm trong More
        if not connect_btn:
            try:
                more_btn = wait.until(EC.element_to_be_clickable((By.XPATH, XPATH_MORE_BTN_MAIN)))
                driver.execute_script("arguments[0].click();", more_btn) #Thay đổi thành arguments[0]
                print("Đã ấn More ngoài")
                time.sleep(2)                
                # #more_btn_xpath = "//button[contains(@aria-label, 'More') and contains(@class, 'artdeco-button')]"
                # #remove_xpath = "//div[@role='button' or @type='button'][contains(., 'Remove Connection') or contains(., 'Unfollow')]"
                # if driver.find_elements(By.XPATH, XPATH_MORE_REMOVE_CONNECTION):
                #     print("Trạng thái: Đã kết nối. (Tìm thấy trong More).")
                #     ActionChains(driver).send_keys(Keys.ESCAPE).perform()
                #     return "CONNECTED"
                # if connect_btn.text == "Pending":
                #     print("🔄 Nút đang chờ xác nhận (Pending).")
                #     return "ALREADY PENDED"    
                
                # print(f"Start finding {XPATH_MORE_CONNECT}")
                # connect_btn = wait.until(EC.element_to_be_clickable((By.XPATH, XPATH_MORE_CONNECT)))
                #print(f"✅ Tìm thấy nút Connect trong More: {connect_btn.tag_name}, {connect_btn.text}, {connect_btn.get_attribute('aria-label')}")
                             
            except Exception as e: 
                print(f"Lỗi: {e}\nKhông tìm thấy nút More với XPATH, bắt đầu dùng actionChains")
                in_search_for_more = True
                tab_count = 0
                max_tabs = 20
                while in_search_for_more and tab_count < max_tabs:
                    actions.send_keys(Keys.TAB).perform()
                    cur_element_more = driver.switch_to.active_element
                    cur_element_more_text = cur_element_more.text.strip()
                    #print(f"Nút hiện tại cho check vị trí More: {cur_element_more_text}")
                    if cur_element_more_text in ["More", "Xem thêm"]:
                        driver.execute_script("arguments[0].click();", cur_element_more)
                        in_search_for_more = False
                    tab_count += 1
                if in_search_for_more:
                    print(f"Bỏ cuộc: Không tìm thấy nút More sau {max_tabs} lần Tab.")
                    return "FAILED"
                print("Đã ấn More bằng actionChains, bắt đầu tìm Connect trong More với actionChains")
                time.sleep(3)
            #Dùng vòng lặp While, detect từng li_item.text trong more modal, nếu pending return "ALREADY PENDED", nếu REMOVE/UNFOLLOW return "CONNECTED", nếu thấy CONNECT thì bấm, còn không thấy gì thì thoát ra và return "FAILED"
            in_more = True
            while in_more:
                time.sleep(random.uniform(0.25, 0.5))
                actions.send_keys(Keys.TAB).perform()
                cur_element = driver.switch_to.active_element
                cur_element_text = cur_element.text.strip()
                print(f"Nút hiện tại cho check trạng thái: {cur_element_text}")
                if cur_element_text == "Pending":
                    print("Trạng thái: Đang chờ xác nhận (Pending). Tìm thấy Pending từ trong More")
                    ActionChains(driver).send_keys(Keys.ESCAPE).perform()
                    return "ALREADY PENDED"
                if cur_element_text in ["Remove connection", "Unfollow"]:
                    print(f"Trạng thái: Đã kết nối.Tìm thấy từ trong More")
                    ActionChains(driver).send_keys(Keys.ESCAPE).perform()
                    return "CONNECTED"
                if cur_element_text in ["Connect", "Connect with note"]:
                    print(f"Trạng thái: Chưa kết nối. Tìm thấy nút Connect từ trong More, chuẩn bị click.")
                    driver.execute_script("arguments[0].click();", cur_element)
                    #actions.send_keys(Keys.SPACE).perform()
                    in_more = False
                

        # Bước 3: Click vào nút Connect
        
        print("🖱️ Đã Click nút Connect. Đang đợi Modal...")
        time.sleep(5) # Đợi popup hiện ra
        try:
            failed_alert_popup = driver.find_element(By.XPATH, XPATH_FAILED_ALERT_POPUP)
            if failed_alert_popup:
                print(f"🔍 Tìm thấy thông báo lỗi: {failed_alert_popup.text}")
                return "RETRY LATER IN 3 DAYS"
        except Exception as e:
            print(f"Không có thông báo lỗi: {str(e)}")
        # Bước 4.1: Xử lý Modal gửi kết nối khi cần mail note xác thực (Thao tác phím để tránh lỗi XPath popup)
        try:
            # label_note = wait.until(EC.presence_of_element_located((By.XPATH, XPATH_NOTE_LABEL)))            
            label_note = driver.execute_script(XPATH_NOTE_LABEL)
            print(f"Tìm thấy label note: {label_note.tag_name} | {label_note.text} | {label_note.aria_role}")
            #Thử với actionChains
            press_multiple_tab(actions, 3, 0.5) #vào ô popup -> vào learnmore -> vào ô nhập
            actions.send_keys(profile_mail).perform()
            time.sleep(2)
            press_multiple_tab(actions, 2, 0.5) #vào nút "Send a note" -> Vào nút "Send without a note"
            print(f"Nút hiện tại: {driver.switch_to.active_element.tag_name} | {driver.switch_to.active_element.text} | {driver.switch_to.active_element.aria_role}")
            actions.send_keys(Keys.SPACE).perform()
            time.sleep(3)            
            return "START PENDING"
            # try:
            #     #driver.execute_script("arguments[0].click();", driver.find_element(By.XPATH, TEXTFIELD_VERIFY_NOTE))
            #     textfield_note = driver.execute_script(TEXTFIELD_VERIFY_NOTE)
            #     driver.execute_script("arguments[0].click();", textfield_note)
            #     print(f"Tìm thấy ô nhập note xác thực email: {driver.switch_to.active_element.tag_name}, đã click vào ô nhập.")
            #     if profile_mail != "":
            #         actions.send_keys(profile_mail).perform()
            #         time.sleep(2)
            #         try:
            #             wait.until(EC.element_to_be_clickable((By.XPATH, BUTTON_SEND_NOTE[0]))).click()
            #             print(f"🚀 Đã gửi yêu cầu kết nối thành công với note xác thực email: {profile_mail}!")
            #             time.sleep(3)
            #         except Exception as e:
            #             print(f"Không tìm thấy nút gửi ghi chú: {str(e)}, tiến hành Actionchains để gửi")
            #             press_multiple_tab(actions, 2, 0.5)
            #             actions.send_keys(Keys.SPACE).perform()
            #             time.sleep(3)
            #             return "START PENDING"
            #     else:
            #         print(f"Không tìm thấy email xác thực: {profile_mail}.")
            #         return "FAILED"
            # except Exception as e:
            #     print(f"❌ Lỗi khi click vào nút textfield ghi chú: {str(e)}, bắt đầu dùng ActionChains")
            #     press_multiple_tab(actions, 3, 0.5)
            #     print(f"Đi đến ô nhập mail: {driver.switch_to.active_element.tag_name} - {driver.switch_to.active_element.aria_role}.")
            #     actions.send_keys(profile_mail).perform()
            #     time.sleep(2)
            #     press_multiple_tab(actions, 2, 0.5)
            #     actions.send_keys(Keys.SPACE).perform()
            #     time.sleep(3)
            #     return "START PENDING"
            
        except:
            print(f"Không tìm thấy Modal mail note xác thực, vào bước 4.2")
            try:
    # Viết JS để vừa tìm vừa click luôn
                click_js = """
                        const host = document.querySelector('#interop-outlet');
    if (host && host.shadowRoot) {
        const buttons = host.shadowRoot.querySelectorAll('button');
        for (let btn of buttons) {
            if (btn.innerText.includes('Send') || btn.getAttribute('aria-label')?.includes('Send')) {
                btn.click();
                return true;
            }
        }
    }
    return false;
                """
                
                # Thực thi script và lấy kết quả trả về
                success = driver.execute_script(click_js)
                
                if success:
                    print("✅ Đã click 'Send without a note' qua Shadow DOM")
                    time.sleep(3)
                    return "START PENDING"
                else:
                    # Nếu JS trả về false, chủ động raise lỗi để nhảy xuống block except
                    raise Exception("Shadow element not found")

            except Exception as e:
                print(f"Không tìm thấy qua JS, thử với ActionChain. Lỗi: {e}")
                # Bước 4.2: Backup bằng phím
                # actions.move_by_offset(1920/2, 80).click().perform()
                # print("Click!")
                time.sleep(1)
                #press_multiple_tab(actions, 3, 0.5)
                actions.key_down(Keys.LEFT_SHIFT).send_keys(Keys.TAB).key_up(Keys.LEFT_SHIFT).perform()
                actions.send_keys(Keys.SPACE).perform()
                time.sleep(2)
                return "START PENDING"
        
                
    except Exception as e:
        print(f"❌ Lỗi tại send_connection: {str(e)}")
        actions.send_keys(Keys.ESCAPE).perform()
        return "FAILED"



def check_connection(driver: webdriver.Chrome, profile_mail: str = ""):
    try:
        # # 1. Cuộn trang trước khi kiểm tra để load đủ dữ liệu
        # human_scroll(driver)
        
        # 2. Kiểm tra nhanh trạng thái "Pending" hoặc "Wait"
        # Dùng text-based XPath để chính xác hơn 
        if driver.find_elements(By.XPATH, XPATH_PENDING_BUTTON):
            print("Trạng thái: Đang chờ xác nhận (Pending). Tìm thấy Pending từ ngoài")
            return "ALREADY PENDED"

        # 3. Kiểm tra nút "Connected" hoặc "Message" (Nếu có Message và không có Connect -> Thường là đã bạn bè)
        # LinkedIn đôi khi hiện nút 'Message'khi đã là bạn bè
        connected_indicators = [
            "//button[contains(., 'Connected')]",
            "//button[contains(@aria-label, 'Remove Connection')]",
            "//span[text()='Connected']"
        ]
        for xpath in connected_indicators:
            if driver.find_elements(By.XPATH, xpath):
                print("Trạng thái: Đã kết nối.")
                return "CONNECTED"

        # Nếu vượt qua hết các check trên mà không return -> Bắt đầu gửi connect
        print("Bắt đầu gọi send_connection - tìm pending trong More và gửi connect nếu chưa pending")
        return send_connection(driver, profile_mail)

    except Exception as e:
        print(f"❌ Lỗi tại check_connection: {str(e)}")
        return f"ERROR: {str(e)}"
        
def main_connect():
    #restore_cookie_from_secret()
    
    # 1. ĐỌC DỮ LIỆU ĐẢM BẢO KHÔNG THIẾU DÒNG/CỘT
    result = sheet.values().get(spreadsheetId=SPREADSHEET_ID, range=RANGE_NAME).execute()
    values = result.get('values', [])
    
    if not values:
        print("ERROR: Không có dữ liệu trong Sheet")
        return
    headers = values[0]
    required_min_cols = 5 
    if len(headers) < required_min_cols:
        headers += [f"Column_{i}" for i in range(len(headers), required_min_cols)]

    data = []
    for row in values[1:]:
        # Làm đầy dòng để khớp với số lượng headers mới
        padded_row = row + [""] * (len(headers) - len(row))
        data.append(padded_row)
        
    df = pd.DataFrame(data, columns=headers)

    # 2. KHỞI TẠO DRIVER & ĐĂNG NHẬP
    driver = get_driver()
    COL_DROPDOWN = "Trạng thái kết nối (đôi khi nút Connect nằm trong nút More)"
    COL_STATUS = "STATUS"
    
    username = os.getenv("LINKEDIN_USERNAME")
    password = os.getenv("LINKEDIN_PASSWORD")
    login(driver, username, password)
    ActionChains(driver).send_keys(Keys.ESCAPE).perform()
    
    send_count = 0

    # 3. VÒNG LẶP XỬ LÝ
    for index, row in df.iterrows():
        print("===========================START==================================")
        if send_count >= MAX_LIMIT:
            break
        profile_link = str(row.iloc[0]).strip()
        profile_mail = str(row.iloc[1]).strip()
        current_status_text = str(row.iloc[3]).strip().upper()
        current_dropdown = str(row.iloc[2]).strip().lower()

        # Kiểm tra nếu dòng này rỗng hoàn toàn (không có link) thì bỏ qua
        if not profile_link or "linkedin.com" not in profile_link:
            continue

        # LOGIC SKIP: Chỉ chạy nếu chưa gửi connect và chưa là bạn bè
        # Chấp nhận các ô trống hoặc giá trị nan
        is_processed = current_dropdown != "" and current_dropdown != "nan" and current_dropdown != "không tồn tại"
        is_connected = current_status_text in ["CONNECTED", "PENDING", "START PENDING", "ALREADY PENDED", "RETRY LATER IN 3 DAYS"]

        if is_processed or is_connected:
            print(f"⏭️ Bỏ qua dòng {index + 2}: {profile_link} (Trạng thái: {current_dropdown})")
            continue

        # THỰC HIỆN KẾT NỐI
        print(f"🚀 Đang xử lý dòng {index + 2}: {profile_link}")
        try:
            driver.get(profile_link)
            #trả về 404 page not found thì bỏ qua            
            time.sleep(random.uniform(5, 6))
            if driver.current_url == "https://www.linkedin.com/404/":
                print(f"⏭️ Bỏ qua dòng {index + 2}: {profile_link} (Trạng thái: 404 Not Found)")
                df.iat[index, 2] = "Không tồn tại"
                df.iat[index, 3] = "ERROR: 404 Not Found | Không tìm thấy Link"
                continue
            ActionChains(driver).send_keys(Keys.ESCAPE).perform()
            driver.save_screenshot(f"before_check_index{index+2}.png")
            # Kiểm tra và gửi connect
            #email_to_fill = row.get("Email để điền khi gặp câu hỏi trog lúc connect", "")
            status = check_connection(driver, profile_mail)
            
            # Cập nhật DataFrame
            #df.at[index, COL_STATUS] = status
            df.iat[index, 3] = status
            if status in ["START PENDING","PENDING"]:
                #df.at[index, COL_DROPDOWN] = "Đã gửi connect"
                df.iat[index, 2] = "Đã gửi connect"
                send_count += 1
                print(f"Đã gửi connect. Tổng connect đã gửi: {send_count} / {MAX_LIMIT}")
                driver.save_screenshot(f"success_sent_index{index+2}_count{send_count}.png")
            elif status in ["ALREADY PENDED", "CONNECTED"]:
                df.iat[index, 2] = "Đã gửi connect"
                driver.save_screenshot(f"success_sent_index{index+2}_count{send_count}.png")
            else:
                df.iat[index, 2] = "Không tồn tại"
                driver.save_screenshot(f"fail_sent_index{index+2}_count{send_count}.png")
            # Nghỉ để tránh bị quét bot
            time.sleep(random.uniform(15, 25))
            
        except Exception as e:
            print(f"❌ Lỗi dòng {index + 2}: {e}")
            driver.save_screenshot(f"fail_sent_index{index+2}_count{send_count}.png")
            df.at[index, COL_STATUS] = "ERROR"

    # 4. CẬP NHẬT LẠI GOOGLE SHEETS DÙNG BATCH UPDATE
    print("📤 Đang chuẩn bị dữ liệu Batch Update...")
    
    # Đảm bảo không có giá trị NaN và chuyển DataFrame thành list (chỉ chứa data, không chứa header)
    df_to_upload = df.fillna("") 
    final_values = df_to_upload.values.tolist()
    
    # Lấy số lượng cột thực tế từ DataFrame
    num_cols = len(df_to_upload.columns)
    last_col_letter = chr(ord('A') + num_cols - 1)
    
    # Lấy số lượng dòng thực tế của dữ liệu
    num_rows_data = len(final_values)
    
    # ĐỊNH NGHĨA VÙNG DỮ LIỆU: Bắt đầu từ A2 đến dòng cuối cùng của dữ liệu
    # Ví dụ: Nếu có 2 dòng dữ liệu, vùng ghi sẽ là A2:E3
    update_range = f"Sheet1!A2:{last_col_letter}{num_rows_data + 1}"

    # Cấu trúc body cho batchUpdate
    batch_update_values_request_body = {
        'valueInputOption': 'RAW',
        'data': [
            {
                'range': update_range,
                'values': final_values
            }
        ]
    }

    try:
        # Sử dụng batchUpdate bắt đầu từ dòng 2
        service.spreadsheets().values().batchUpdate(
            spreadsheetId=SPREADSHEET_ID,
            body=batch_update_values_request_body
        ).execute()
        print(f"✅ Batch Update thành công vùng {update_range}!")
    except Exception as e:
        print(f"❌ Lỗi Batch Update: {e}")
        # Backup plan: Chia nhỏ (Chunking) nhưng vẫn giữ logic bắt đầu từ dòng 2
        print("🔄 Đang thử gửi lại theo phương thức Chia nhỏ (Chunking)...")
        chunk_size = 5
        for i in range(0, len(final_values), chunk_size):
            chunk = final_values[i : i + chunk_size]
            r_start = i + 2 # Luôn bắt đầu từ dòng 2
            r_end = r_start + len(chunk) - 1
            c_range = f"Sheet1!A{r_start}:{last_col_letter}{r_end}"
            service.spreadsheets().values().update(
                spreadsheetId=SPREADSHEET_ID,
                range=c_range,
                valueInputOption='RAW',
                body={'values': chunk}
            ).execute()
    finally:
        print("Đã hoàn thành cập nhật")

if __name__ == "__main__":
    main_connect()
